from opt_einsum import contract


def build_right_sigma_ai(V_t, f, u, R0, R1, R2, L0, L1, L2, t2, Hbar, o, v, np):

    sigma_ai = 2.0 * contract("eami,me->ai", R2, Hbar["ov"])
    sigma_ai -= contract("eaim,me->ai", R2, Hbar["ov"])

    sigma_ai += contract("ei,ae->ai", R1, Hbar["vv"])
    sigma_ai -= contract("mi,am->ai", Hbar["oo"], R1)

    sigma_ai += 2.0 * contract("maei,em->ai", Hbar["ovvo"], R1)
    sigma_ai -= contract("maie,em->ai", Hbar["ovov"], R1)

    sigma_ai += 2.0 * contract("efim,amef->ai", R2, Hbar["vovv"])
    sigma_ai -= contract("efim,amfe->ai", R2, Hbar["vovv"])
    sigma_ai -= 2.0 * contract("mnie,aemn->ai", Hbar["ooov"], R2)
    sigma_ai += contract("nmie,aemn->ai", Hbar["ooov"], R2)

    return sigma_ai


def build_right_sigma_abij(
    V_t, f, u, R0, R1, R2, L0, L1, L2, t2, Hbar, o, v, np
):

    tmp = u[o, o, v, v].copy()
    Loovv = 2.0 * tmp - tmp.swapaxes(2, 3)

    sigma_abij = contract("ei,abej->abij", R1, Hbar["vvvo"])
    sigma_abij -= contract("mbij,am->abij", Hbar["ovoo"], R1)

    Zvv = 2.0 * contract("amef,fm->ae", Hbar["vovv"], R1)
    Zvv -= contract("amfe,fm->ae", Hbar["vovv"], R1)
    Zvv -= contract("afnm,nmef->ae", R2, Loovv)
    sigma_abij += contract("ebij,ae->abij", t2, Zvv)

    Zoo = -2.0 * contract("mnie,en->mi", Hbar["ooov"], R1)
    Zoo += contract("nmie,en->mi", Hbar["ooov"], R1)
    Zoo -= contract("mnef,efin->mi", Loovv, R2)
    sigma_abij += contract("mi,abmj->abij", Zoo, t2)

    sigma_abij += contract("ebij,ae->abij", R2, Hbar["vv"])
    sigma_abij -= contract("mi,abmj->abij", Hbar["oo"], R2)

    sigma_abij += 0.5 * contract("mnij,abmn->abij", Hbar["oooo"], R2)
    sigma_abij += 0.5 * contract("efij,abef->abij", R2, Hbar["vvvv"])

    sigma_abij -= contract("ebim,maje->abij", R2, Hbar["ovov"])
    sigma_abij -= contract("eaim,mbej->abij", R2, Hbar["ovvo"])

    sigma_abij += 2.0 * contract("eami,mbej->abij", R2, Hbar["ovvo"])
    sigma_abij -= contract("eami,mbje->abij", R2, Hbar["ovov"])
    return sigma_abij + sigma_abij.swapaxes(0, 1).swapaxes(2, 3)


def build_right_sigma_ai_drudge(
    V_t, f, u, R0, R1, R2, L0, L1, L2, t2, o, v, np
):

    """
    <S|[Hbar,R]|0> generated by drudge.
    """

    sigma_ai = 2 * contract("jb,abij->ai", f[o, v], R2)
    sigma_ai -= contract("jb,abji->ai", f[o, v], R2)

    sigma_ai += contract("bi,ab->ai", R1, f[v, v])
    sigma_ai += contract("bi,acjk,jkcb->ai", R1, t2, u[o, o, v, v])
    sigma_ai -= 2 * contract("bi,acjk,jkbc->ai", R1, t2, u[o, o, v, v])

    sigma_ai -= contract("aj,ji->ai", R1, f[o, o])
    sigma_ai += contract("aj,bcik,jkcb->ai", R1, t2, u[o, o, v, v])

    sigma_ai += contract("bj,acki,jkcb->ai", R1, t2, u[o, o, v, v])

    sigma_ai -= 2 * contract("aj,bcik,jkbc->ai", R1, t2, u[o, o, v, v])

    sigma_ai -= 2 * contract("bj,acik,jkcb->ai", R1, t2, u[o, o, v, v])

    sigma_ai -= 2 * contract("bj,acki,jkbc->ai", R1, t2, u[o, o, v, v])

    sigma_ai += 4 * contract("bj,acik,jkbc->ai", R1, t2, u[o, o, v, v])

    sigma_ai += contract("abjk,kjib->ai", R2, u[o, o, o, v])

    sigma_ai -= 2 * contract("abjk,jkib->ai", R2, u[o, o, o, v])

    sigma_ai -= contract("bj,ajbi->ai", R1, u[v, o, v, o])

    sigma_ai += 2 * contract("bj,ajib->ai", R1, u[v, o, o, v])

    sigma_ai -= contract("bcij,ajcb->ai", R2, u[v, o, v, v])

    sigma_ai += 2 * contract("bcij,ajbc->ai", R2, u[v, o, v, v])

    return sigma_ai


def build_right_sigma_abij_drudge(
    V_t, f, u, R0, R1, R2, L0, L1, L2, t2, o, v, np
):
    """
    <D|[Hbar,R]|0> generated by drudge.
    """
    sigma_abij = contract("ci,abcj->abij", R1, u[v, v, v, o])

    sigma_abij += contract("cj,abic->abij", R1, u[v, v, o, v])

    sigma_abij += contract("ac,bcji->abij", f[v, v], R2)

    sigma_abij += contract("bc,acij->abij", f[v, v], R2)

    sigma_abij += contract("abkl,klij->abij", R2, u[o, o, o, o])

    sigma_abij += contract("cdij,abcd->abij", R2, u[v, v, v, v])

    sigma_abij -= contract("ak,bkji->abij", R1, u[v, o, o, o])

    sigma_abij -= contract("bk,akij->abij", R1, u[v, o, o, o])

    sigma_abij -= contract("ki,abkj->abij", f[o, o], R2)

    sigma_abij -= contract("kj,abik->abij", f[o, o], R2)

    sigma_abij += contract("ak,bcjl,lkic->abij", R1, t2, u[o, o, o, v])

    sigma_abij += contract("ak,bcli,klcj->abij", R1, t2, u[o, o, v, o])

    sigma_abij += contract("ak,bclj,klic->abij", R1, t2, u[o, o, o, v])

    sigma_abij += contract("bk,acil,klcj->abij", R1, t2, u[o, o, v, o])

    sigma_abij += contract("bk,acli,lkcj->abij", R1, t2, u[o, o, v, o])

    sigma_abij += contract("bk,aclj,lkic->abij", R1, t2, u[o, o, o, v])

    sigma_abij += contract("ci,abkl,klcj->abij", R1, t2, u[o, o, v, o])

    sigma_abij += contract("cj,abkl,klic->abij", R1, t2, u[o, o, o, v])

    sigma_abij += contract("ck,abil,lkcj->abij", R1, t2, u[o, o, v, o])

    sigma_abij += contract("ck,ablj,klic->abij", R1, t2, u[o, o, o, v])

    sigma_abij -= 2 * contract("ak,bcjl,klic->abij", R1, t2, u[o, o, o, v])

    sigma_abij -= 2 * contract("bk,acil,lkcj->abij", R1, t2, u[o, o, v, o])

    sigma_abij -= 2 * contract("ck,abil,klcj->abij", R1, t2, u[o, o, v, o])

    sigma_abij -= 2 * contract("ck,ablj,lkic->abij", R1, t2, u[o, o, o, v])

    sigma_abij -= contract("acik,bkcj->abij", R2, u[v, o, v, o])

    sigma_abij -= contract("acki,bkjc->abij", R2, u[v, o, o, v])

    sigma_abij -= contract("ackj,bkci->abij", R2, u[v, o, v, o])

    sigma_abij -= contract("bcjk,akci->abij", R2, u[v, o, v, o])

    sigma_abij -= contract("bcki,akcj->abij", R2, u[v, o, v, o])

    sigma_abij -= contract("bckj,akic->abij", R2, u[v, o, o, v])

    sigma_abij += 2 * contract("acik,bkjc->abij", R2, u[v, o, o, v])

    sigma_abij += 2 * contract("bcjk,akic->abij", R2, u[v, o, o, v])

    sigma_abij -= contract("ak,kc,bcji->abij", R1, f[o, v], t2)

    sigma_abij -= contract("bk,kc,acij->abij", R1, f[o, v], t2)

    sigma_abij -= contract("ci,kc,abkj->abij", R1, f[o, v], t2)

    sigma_abij -= contract("cj,kc,abik->abij", R1, f[o, v], t2)

    sigma_abij -= contract("ak,cdij,bkdc->abij", R1, t2, u[v, o, v, v])

    sigma_abij -= contract("bk,cdij,akcd->abij", R1, t2, u[v, o, v, v])

    sigma_abij -= contract("ci,adkj,bkdc->abij", R1, t2, u[v, o, v, v])

    sigma_abij -= contract("ci,bdjk,akdc->abij", R1, t2, u[v, o, v, v])

    sigma_abij -= contract("ci,bdkj,akcd->abij", R1, t2, u[v, o, v, v])

    sigma_abij -= contract("cj,adik,bkdc->abij", R1, t2, u[v, o, v, v])

    sigma_abij -= contract("cj,adki,bkcd->abij", R1, t2, u[v, o, v, v])

    sigma_abij -= contract("cj,bdki,akdc->abij", R1, t2, u[v, o, v, v])

    sigma_abij -= contract("ck,adij,bkcd->abij", R1, t2, u[v, o, v, v])

    sigma_abij -= contract("ck,bdji,akcd->abij", R1, t2, u[v, o, v, v])

    sigma_abij += 2 * contract("ci,bdjk,akcd->abij", R1, t2, u[v, o, v, v])

    sigma_abij += 2 * contract("cj,adik,bkcd->abij", R1, t2, u[v, o, v, v])

    sigma_abij += 2 * contract("ck,adij,bkdc->abij", R1, t2, u[v, o, v, v])

    sigma_abij += 2 * contract("ck,bdji,akdc->abij", R1, t2, u[v, o, v, v])

    sigma_abij += contract("abik,cdlj,klcd->abij", R2, t2, u[o, o, v, v])

    sigma_abij += contract("abkj,cdil,kldc->abij", R2, t2, u[o, o, v, v])

    sigma_abij += contract("abkl,cdij,klcd->abij", R2, t2, u[o, o, v, v])

    sigma_abij += contract("acij,bdkl,kldc->abij", R2, t2, u[o, o, v, v])

    sigma_abij += contract("acik,bdlj,kldc->abij", R2, t2, u[o, o, v, v])

    sigma_abij += contract("acki,bdjl,kldc->abij", R2, t2, u[o, o, v, v])

    sigma_abij += contract("acki,bdlj,klcd->abij", R2, t2, u[o, o, v, v])

    sigma_abij += contract("ackj,bdli,kldc->abij", R2, t2, u[o, o, v, v])

    sigma_abij += contract("ackl,bdji,klcd->abij", R2, t2, u[o, o, v, v])

    sigma_abij += contract("bcji,adkl,kldc->abij", R2, t2, u[o, o, v, v])

    sigma_abij += contract("bcjk,adli,kldc->abij", R2, t2, u[o, o, v, v])

    sigma_abij += contract("bcki,adlj,kldc->abij", R2, t2, u[o, o, v, v])

    sigma_abij += contract("bckj,adil,kldc->abij", R2, t2, u[o, o, v, v])

    sigma_abij += contract("bckj,adli,klcd->abij", R2, t2, u[o, o, v, v])

    sigma_abij += contract("bckl,adij,klcd->abij", R2, t2, u[o, o, v, v])

    sigma_abij += contract("cdij,abkl,klcd->abij", R2, t2, u[o, o, v, v])

    sigma_abij += contract("cdik,ablj,klcd->abij", R2, t2, u[o, o, v, v])

    sigma_abij += contract("cdkj,abil,kldc->abij", R2, t2, u[o, o, v, v])

    sigma_abij -= 2 * contract("abik,cdlj,kldc->abij", R2, t2, u[o, o, v, v])

    sigma_abij -= 2 * contract("abkj,cdil,klcd->abij", R2, t2, u[o, o, v, v])

    sigma_abij -= 2 * contract("acij,bdkl,klcd->abij", R2, t2, u[o, o, v, v])

    sigma_abij -= 2 * contract("acik,bdjl,kldc->abij", R2, t2, u[o, o, v, v])

    sigma_abij -= 2 * contract("acik,bdlj,klcd->abij", R2, t2, u[o, o, v, v])

    sigma_abij -= 2 * contract("acki,bdjl,klcd->abij", R2, t2, u[o, o, v, v])

    sigma_abij -= 2 * contract("ackl,bdji,kldc->abij", R2, t2, u[o, o, v, v])

    sigma_abij -= 2 * contract("bcji,adkl,klcd->abij", R2, t2, u[o, o, v, v])

    sigma_abij -= 2 * contract("bcjk,adil,kldc->abij", R2, t2, u[o, o, v, v])

    sigma_abij -= 2 * contract("bcjk,adli,klcd->abij", R2, t2, u[o, o, v, v])

    sigma_abij -= 2 * contract("bckj,adil,klcd->abij", R2, t2, u[o, o, v, v])

    sigma_abij -= 2 * contract("bckl,adij,kldc->abij", R2, t2, u[o, o, v, v])

    sigma_abij -= 2 * contract("cdik,ablj,kldc->abij", R2, t2, u[o, o, v, v])

    sigma_abij -= 2 * contract("cdkj,abil,klcd->abij", R2, t2, u[o, o, v, v])

    sigma_abij += 4 * contract("acik,bdjl,klcd->abij", R2, t2, u[o, o, v, v])

    sigma_abij += 4 * contract("bcjk,adil,klcd->abij", R2, t2, u[o, o, v, v])

    return sigma_abij
